apiVersion: v1
kind: Service
metadata:
  name: telephone-cli-service
  namespace: telephone
spec:
  selector:
    app: telephone-cli
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
